package Biblioteca;


/**
* Biblioteca/GestionBiblioteca.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* Saturday, March 29, 2025 10:31:36 AM UTC
*/


// Define la interfaz para el sistema de gestión de la biblioteca
public interface GestionBiblioteca extends GestionBibliotecaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionBiblioteca
